#!/bin/bash


SITES_ENABLED_DEFAULT_FILENAME="/etc/freeradius/3.0/sites-enabled/default"
#LISTEN_AUTH_ADDR="69.69.69.69"
#LISTEN_ACCT_ADDR="420.420.420.420"


#sudo cp "${SITES_ENABLED_DEFAULT_FILENAME}" "${SITES_ENABLED_DEFAULT_FILENAME}".bakup

# clear previous content
echo -e "server default {\n" > "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   listen {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       type = auth\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       ipaddr = ${LISTEN_AUTH_ADDR}\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       port = 0\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       limit {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "           max_connections = 16\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "           lifetime = 0\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "           idle_timeout = 30\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   }" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   listen {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       ipaddr = ${LISTEN_ACCT_ADDR}\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       port = 0\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       type = acct\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       limit {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   authorize {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       filter_username\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       preprocess\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       suffix\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       eap {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "           ok = return\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       files\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       expiration\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       logintime\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       Autz-Type New-TLS-Connection {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "           ok\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   authenticate {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       eap\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   preacct {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       preprocess\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       acct_unique\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       suffix\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       files\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   accounting {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       detail\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       unix\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       exec\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       attr_filter.accounting_response\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   session {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   post-auth {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       if (session-state:User-Name && reply:User-Name && request:User-Name && (reply:User-Name == request:User-Name)) {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "           update reply {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "               &User-Name !* ANY\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "           }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   update {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       &reply: += &session-state:\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   remove_reply_message_if_eap\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   Post-Auth-Type REJECT {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       eap\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       remove_reply_message_if_eap\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   Post-Auth-Type Challenge {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   Post-Auth-Type Client-Lost {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       if (EAP-Key-Name && &reply:EAP-Session-Id) {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "           update reply {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "               &EAP-Key-Name := &reply:EAP-Session-Id\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "           }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   pre-proxy {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   post-proxy {\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "       eap\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "   }\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
echo -e "}\n" >> "${SITES_ENABLED_DEFAULT_FILENAME}"
